using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using THS.Infrastructure.Extensions;

namespace MES.Order.UI
{
    public partial class ChartData : UserControl
    {
        public ChartData()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            MES.Order.DAL.EntityFramework.ProductsDbContext dbContext = new MES.Order.DAL.EntityFramework.ProductsDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.ProductsOrders.Load();
            // This line of code is generated by Data Source Configuration Wizard
            var productsOrders = dbContext.ProductsOrders.Local.ToBindingList();
            // var enumerable     = productsOrders.Where(x=>x.OrderDate.Value.Year ==DateTime.Today.Year & x.OrderDate.Value.Month ==DateTime.Today.Month).ToList();
            // enumerable.ForEach(x=>x._OrderDate=x.OrderDate.Value.ToTaiwanCalendar("yyyMM"));
            // productsOrdersBindingSource.DataSource = dbContext.ProductsOrders.Local.ToBindingList();
            productsOrdersBindingSource.DataSource = productsOrders;
        }
    }
}
