//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Order.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>家電用品</string>
  <string>冷凍食品</string>
  <string>常溫食品</string>
  <string>居家百貨</string>
  <string>3C產品</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProductType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProductType"]));
            }
            set {
                this["ProductType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>紅</string>
  <string>白</string>
  <string>黃</string>
  <string>綠</string>
  <string>藍</string>
  <string>紫</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColorSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColorSpec"]));
            }
            set {
                this["ColorSpec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>XS</string>
  <string>S</string>
  <string>M</string>
  <string>L</string>
  <string>XL</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SizeSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SizeSpec"]));
            }
            set {
                this["SizeSpec"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Y:已取貨</string>
  <string>N:未取貨</string>
  <string>已取貨</string>
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrderStatus {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrderStatus"]));
            }
        }
    }
}
