//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES.Order.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>家電用品</string>
  <string>冷凍食品</string>
  <string>常溫食品</string>
  <string>居家百貨</string>
  <string>3C產品</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ProductType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProductType"]));
            }
            set {
                this["ProductType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>紅</string>
  <string>白</string>
  <string>黃</string>
  <string>綠</string>
  <string>藍</string>
  <string>紫</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColorSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColorSpec"]));
            }
            set {
                this["ColorSpec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>XS</string>
  <string>S</string>
  <string>M</string>
  <string>L</string>
  <string>XL</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SizeSpec {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SizeSpec"]));
            }
            set {
                this["SizeSpec"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Y:已取貨</string>
  <string>N:未取貨</string>
  <string>已取貨</string>
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrderStatus {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrderStatus"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" KK-PC ")]
        public string DefaultLocation {
            get {
                return ((string)(this["DefaultLocation"]));
            }
            set {
                this["DefaultLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=KK-PC;initial catalog=CoupleOrder;integrated security=True;MultipleAc" +
            "tiveResultSets=True;App=EntityFramework")]
        public string KKPCDbContext {
            get {
                return ((string)(this["KKPCDbContext"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=KK-PC-OLD\\Order;initial catalog=CoupleOrder;integrated security=True;" +
            "MultipleActiveResultSets=True;App=EntityFramework      ")]
        public string KKPCOLDDbContext {
            get {
                return ((string)(this["KKPCOLDDbContext"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(" data source=S03CSY\\SQLEXPRESS;initial catalog=CoupleOrder;integrated security=Tr" +
            "ue;MultipleActiveResultSets=True;App=EntityFramework")]
        public string S03CSYDbContext {
            get {
                return ((string)(this["S03CSYDbContext"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(" data source=SuYun\\SQLEXPRESS;initial catalog=CoupleOrder;integrated security=Tru" +
            "e;MultipleActiveResultSets=True;App=EntityFramework")]
        public string SuYunDbContext {
            get {
                return ((string)(this["SuYunDbContext"]));
            }
        }
    }
}
